# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: usuario
  password: 186425 # from psql setup, see Postgresql  
  host: localhost

development:
  <<: *default
  database: ceiba_team_development

test:
  <<: *default
  database: ceiba_team_test

production:
  <<: *default
  database: ceiba_team_production
